version: '2'
services:
  frontend:
    image: nginx
    ports: 
      - "80:8000"
    volumes:
      - ./front:/data
      - ./nginx.conf:/etc/nginx/nginx.conf
  db:
    image: mysql
    ports: 
      - "3306:3306"
    networks:
      - backend 
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: ppsus
      MYSQL_USER: ppsus
      MYSQL_PASSWORD: rede243
  backend:
    build: backend
    ports: 
      - "8000:8000"
    networks:
      - backend 
    environment:
      DBNAME: ppsus
      DBUSER: ppsus
      DBPASS: rede243
      DBHOST: db
      
networks:
  backend:
    driver: bridge