# Generated by Django 2.0.2 on 2018-02-12 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edmonton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField()),
                ('fragilidade', models.CharField(max_length=1, null=True)),
                ('fatores', models.CharField(max_length=300, null=True)),
                ('q1_cognicao', models.PositiveSmallIntegerField(choices=[(1, 'Aprovado'), (2, 'Reprovado com erros mínimos'), (3, 'Reprovado com erros significantes')], null=True)),
                ('q1_foto_relogio', models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('q2_estado_saude_A', models.PositiveSmallIntegerField(choices=[(1, '0'), (2, '1 ou 2'), (3, '3 ou +')], null=True)),
                ('q2_estado_saude_B', models.PositiveSmallIntegerField(choices=[(1, 'Excelente'), (2, 'Muito boa'), (3, 'Boa'), (4, 'Razoável'), (5, 'Ruim')], null=True)),
                ('q3_ind_func', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Preparar refeição (cozinhar)'), ('2', 'Usar o telefone'), ('3', 'Transporte (se locomover)'), ('4', 'Lavar a roupa'), ('5', 'Cuidar da casa (limpar / arrumar)'), ('6', 'Cuidar do dinheiro'), ('7', 'Fazer compras'), ('8', 'Tomar remédios')], max_length=15, null=True)),
                ('q4_sup_social', models.PositiveSmallIntegerField(choices=[(1, 'Sempre'), (2, 'As vezes'), (3, 'Nunca')], null=True)),
                ('q5_medicamento_A', models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não')], null=True)),
                ('q5_medicamento_B', models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não')], null=True)),
                ('q6_nutricao', models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não')], null=True)),
                ('q7_humor', models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não')], null=True)),
                ('q8_continencia', models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não')], null=True)),
                ('q9_desemp_func', models.PositiveSmallIntegerField(choices=[(1, '0-10 segundos'), (2, '11-20 segundos'), (3, '21 segundos ou mais')], null=True)),
                ('q9_desemp_func_tempo', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nro_sus', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('end_bairo', models.CharField(max_length=100, null=True)),
                ('end_rua', models.CharField(max_length=100, null=True)),
                ('end_numero', models.CharField(max_length=100, null=True)),
                ('cep', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('end_bairro', models.CharField(max_length=100, null=True)),
                ('end_rua', models.CharField(max_length=100, null=True)),
                ('end_numero', models.IntegerField(null=True)),
                ('cep', models.CharField(max_length=8, null=True)),
                ('telefone', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='ppsus_app.Posto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subjetiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField()),
                ('fragilidade', models.CharField(max_length=1, null=True)),
                ('fatores', models.CharField(max_length=300, null=True)),
                ('q1_perdeu_peso', models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não sabe'), (4, 'Não respondeu')], null=True)),
                ('q1_perdeu_peso_kg', models.FloatField(null=True)),
                ('q2_ativ_fisica', models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não sabe'), (4, 'Não respondeu')], null=True)),
                ('q3_red_forca', models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não sabe'), (4, 'Não respondeu')], null=True)),
                ('q4_red_caminhada', models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não sabe'), (4, 'Não respondeu')], null=True)),
                ('q5_fadiga', models.PositiveSmallIntegerField(choices=[(1, 'Nunca ou raramente'), (2, 'Às vezes'), (3, 'Frequentemente'), (4, 'Sempre')], null=True)),
                ('q6_desanimo', models.PositiveSmallIntegerField(choices=[(1, 'Nunca ou raramente'), (2, 'Às vezes'), (3, 'Frequentemente'), (4, 'Sempre')], null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjetiva', to='ppsus_app.Paciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjetiva', to=settings.AUTH_USER_MODEL)),
                ('usuario_edit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjetiva_edit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='edmonton',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edmonton', to='ppsus_app.Paciente'),
        ),
        migrations.AddField(
            model_name='edmonton',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edmonton', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edmonton',
            name='usuario_edit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edmonton_edit', to=settings.AUTH_USER_MODEL),
        ),
    ]
