# Generated by Django 2.0.2 on 2018-02-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppsus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='ppsus_app.Posto'),
        ),
    ]
