# Generated by Django 2.0.2 on 2018-02-13 18:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ppsus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edmonton',
            name='data_fim',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q1_cognicao',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aprovado'), (2, 'Reprovado com erros mínimos'), (3, 'Reprovado com erros significantes')]),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q1_foto_relogio',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q2_estado_saude_A',
            field=models.PositiveSmallIntegerField(choices=[(1, '0'), (2, '1 ou 2'), (3, '3 ou +')]),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q2_estado_saude_B',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Excelente'), (2, 'Muito boa'), (3, 'Boa'), (4, 'Razoável'), (5, 'Ruim')]),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q3_ind_func',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Preparar refeição (cozinhar)'), ('2', 'Usar o telefone'), ('3', 'Transporte (se locomover)'), ('4', 'Lavar a roupa'), ('5', 'Cuidar da casa (limpar / arrumar)'), ('6', 'Cuidar do dinheiro'), ('7', 'Fazer compras'), ('8', 'Tomar remédios')], max_length=15),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q4_sup_social',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sempre'), (2, 'As vezes'), (3, 'Nunca')]),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q5_medicamento_A',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não')]),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q5_medicamento_B',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não')]),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q6_nutricao',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não')]),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q7_humor',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não')]),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q8_continencia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não')]),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q9_desemp_func',
            field=models.PositiveSmallIntegerField(choices=[(1, '0-10 segundos'), (2, '11-20 segundos'), (3, '21 segundos ou mais')]),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q9_desemp_func_tempo',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='subjetiva',
            name='data_fim',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subjetiva',
            name='q1_perdeu_peso',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não sabe'), (4, 'Não respondeu')]),
        ),
        migrations.AlterField(
            model_name='subjetiva',
            name='q2_ativ_fisica',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não sabe'), (4, 'Não respondeu')]),
        ),
        migrations.AlterField(
            model_name='subjetiva',
            name='q3_red_forca',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não sabe'), (4, 'Não respondeu')]),
        ),
        migrations.AlterField(
            model_name='subjetiva',
            name='q4_red_caminhada',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sim'), (2, 'Não'), (3, 'Não sabe'), (4, 'Não respondeu')]),
        ),
        migrations.AlterField(
            model_name='subjetiva',
            name='q5_fadiga',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca ou raramente'), (2, 'Às vezes'), (3, 'Frequentemente'), (4, 'Sempre')]),
        ),
        migrations.AlterField(
            model_name='subjetiva',
            name='q6_desanimo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nunca ou raramente'), (2, 'Às vezes'), (3, 'Frequentemente'), (4, 'Sempre')]),
        ),
    ]
