# Generated by Django 2.0.2 on 2018-02-17 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppsus_app', '0002_auto_20180214_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='posto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='ppsus_app.Posto'),
            preserve_default=False,
        ),
    ]
