# Generated by Django 2.0.2 on 2018-02-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppsus_app', '0004_auto_20180218_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edmonton',
            name='q9_desemp_func_tempo',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
