# Generated by Django 2.0.2 on 2018-02-21 13:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ppsus_app', '0006_auto_20180221_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edmonton',
            name='q3_ind_func',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Preparar refeição (cozinhar)'), ('2', 'Usar o telefone'), ('3', 'Transporte (se locomover)'), ('4', 'Lavar a roupa'), ('5', 'Cuidar da casa (limpar / arrumar)'), ('6', 'Cuidar do dinheiro'), ('7', 'Fazer compras'), ('8', 'Tomar remédios')], max_length=15, null=True),
        ),
    ]
