# Generated by Django 2.0.2 on 2018-02-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppsus_app', '0007_auto_20180221_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q1_foto_relogio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edmonton', to='ppsus_app.Document'),
        ),
    ]
