# Generated by Django 2.0.2 on 2018-03-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppsus_app', '0008_auto_20180223_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d/'),
        ),
    ]
