# Generated by Django 2.0.2 on 2018-03-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppsus_app', '0009_auto_20180306_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Homem'), (1, 'Mulher')], null=True),
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q1_foto_relogio',
            field=models.CharField(max_length=200),
        ),
    ]
