# Generated by Django 2.0.2 on 2018-05-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppsus_app', '0010_auto_20180315_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='edmonton',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjetiva',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edmonton',
            name='q9_desemp_func_tempo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Masculino'), (1, 'Feminino')], null=True),
        ),
    ]
