# Generated by Django 2.0.2 on 2018-05-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppsus_app', '0011_auto_20180503_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edmonton',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subjetiva',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
