# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.IntegerField(blank=True)),
                ('endereco', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('telefone', models.CharField(blank=True, max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=1)),
                ('permissao', models.IntegerField()),
                ('fk_post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ppsus_app.Posto')),
            ],
        ),
    ]
