# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppsus_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edmonton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('q1_cognicao', models.IntegerField(blank=True)),
                ('q1_cognicao_edit', models.IntegerField(blank=True)),
                ('q1_foto_relogio', models.ImageField(blank=True, upload_to='fotos_relogio/')),
                ('q2_estado_saude_A', models.IntegerField(blank=True)),
                ('q2_estado_saude_B', models.IntegerField(blank=True)),
                ('q3_ind_func', models.IntegerField(blank=True)),
                ('q4_sup_social', models.IntegerField(blank=True)),
                ('q5_medicamento_A', models.IntegerField(blank=True)),
                ('q6_nutricao', models.IntegerField(blank=True)),
                ('q7_humor', models.IntegerField(blank=True)),
                ('q8_continencia', models.IntegerField(blank=True)),
                ('q9_desemp_func', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nro_sus', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjetiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('q1_perdeu_peso', models.IntegerField(blank=True)),
                ('q1_perdeu_peso_kg', models.FloatField(blank=True)),
                ('q2_ativ_fisica', models.IntegerField(blank=True)),
                ('q3_red_forca', models.IntegerField(blank=True)),
                ('q4_red_caminhada', models.IntegerField(blank=True)),
                ('q4_tempo_caminhada', models.TimeField(blank=True)),
                ('q5_fadiga', models.IntegerField(blank=True)),
                ('q6_desanimo', models.IntegerField(blank=True)),
                ('fk_paciente_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppsus_app.Paciente')),
                ('fk_usuario_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppsus_app.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='edmonton',
            name='fk_paciente_ed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppsus_app.Paciente'),
        ),
        migrations.AddField(
            model_name='edmonton',
            name='fk_usuario_ed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppsus_app.Usuario'),
        ),
        migrations.AddField(
            model_name='edmonton',
            name='fk_usuario_edit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_edit_set', to='ppsus_app.Usuario'),
        ),
    ]
